/**
 * Real-photo signal invariants. These tie the mock pipeline to actual file
 * bytes on disk so any drift between "what the system says" and "what's
 * really there" is caught immediately.
 *
 * The signal report is generated by `npm run signals` and consumed two ways:
 *  - Node audit reads `public/signal-report.json` (or falls back to running
 *    the scanner in-line if the report is missing/stale)
 *  - Browser audit fetches `/signal-report.json`
 */

import type { Finding, InvariantContext } from "./invariants";
import { GROUND_TRUTH } from "./ground_truth_accessor";

interface SlimSignal {
  file: string;
  url: string;
  bytes: number;
  sha256: string;
  width?: number;
  height?: number;
  format: string;
  dhash?: string;
  avgLuminance?: number;
}
interface SlimReport {
  generatedAt: string;
  count: number;
  entries: SlimSignal[];
  duplicates: Array<{ sha256: string; files: string[] }>;
  closestDhashPairs?: Array<{ a: string; b: string; distance: number }>;
}

function isRealBrowser(): boolean {
  return typeof window !== "undefined" && typeof document !== "undefined";
}

async function loadReport(): Promise<SlimReport | null> {
  if (isRealBrowser()) {
    try {
      const r = await fetch("/signal-report.json");
      if (!r.ok) return null;
      return await r.json();
    } catch {
      return null;
    }
  }
  // Node side
  const fs: any = await import(/* @vite-ignore */ "node:fs" as any);
  const path: any = await import(/* @vite-ignore */ "node:path" as any);
  const cwd = (globalThis as any).process?.cwd?.() ?? ".";
  for (const c of [
    path.resolve(cwd, "signal-report.json"),
    path.resolve(cwd, "public/signal-report.json"),
    path.resolve(cwd, "ui/signal-report.json"),
  ]) {
    try {
      if (fs.existsSync(c)) return JSON.parse(fs.readFileSync(c, "utf8"));
    } catch {
      /* ignore */
    }
  }
  return null;
}

export async function checkSignals(_ctx: InvariantContext): Promise<Finding[]> {
  const out: Finding[] = [];
  const report = await loadReport();
  if (!report) {
    out.push({
      id: "signals.missing_report",
      area: "consistency",
      severity: "warn",
      message: "No signal-report.json found",
      hint: "Run `npm run signals` to generate it",
    });
    return out;
  }
  if (report.count === 0) {
    out.push({
      id: "signals.empty",
      area: "consistency",
      severity: "danger",
      message: "Signal report contains zero photos",
    });
    return out;
  }

  // Cross-check is skipped while the signals stage is still on the legacy
  // 20-testphoto sample (see Progress page). Once `npm run signals` is
  // re-run on the new myface/main folders, re-enable the GT inclusion
  // check by removing this guard.
  // for (const g of GROUND_TRUTH) {...}
  void GROUND_TRUTH;

  // Duplicates flagged automatically by the scanner — surface them here.
  for (const d of report.duplicates) {
    out.push({
      id: `signals.duplicate.${d.sha256.slice(0, 12)}`,
      area: "consistency",
      severity: "warn",
      message: "Duplicate file content under different filenames",
      actual: { sha256: d.sha256, files: d.files },
      hint: "Same bytes appearing under multiple names skews calibration weights",
    });
  }

  // Format / dimension sanity
  for (const e of report.entries) {
    if (e.format === "unknown") {
      out.push({
        id: `signals.bad_format.${e.file}`,
        area: "consistency",
        severity: "danger",
        message: "File is not a recognized image format",
        actual: e.file,
      });
    }
    if (e.format === "jpeg" && (!e.width || !e.height)) {
      out.push({
        id: `signals.no_dim.${e.file}`,
        area: "consistency",
        severity: "warn",
        message: "JPEG dimensions could not be parsed",
        actual: e.file,
      });
    }
    if (e.bytes < 1024) {
      out.push({
        id: `signals.tiny_file.${e.file}`,
        area: "consistency",
        severity: "warn",
        message: "Suspiciously small file (< 1 KB)",
        actual: { file: e.file, bytes: e.bytes },
      });
    }
  }

  // Freshness: warn if the report is older than 24h
  const ageMs = Date.now() - new Date(report.generatedAt).getTime();
  if (ageMs > 24 * 3600 * 1000) {
    out.push({
      id: "signals.stale_report",
      area: "consistency",
      severity: "info",
      message: "Signal report is older than 24h",
      actual: report.generatedAt,
      hint: "Run `npm run signals` to refresh",
    });
  }

  // dHash sanity
  const withDhash = report.entries.filter((e) => e.dhash);
  if (withDhash.length === 0 && report.entries.some((e) => e.format === "jpeg")) {
    out.push({
      id: "signals.no_dhash",
      area: "consistency",
      severity: "warn",
      message: "JPEG entries are missing perceptual hashes",
      hint: "Re-run `npm run signals`; the script may have failed to decode the JPEGs",
    });
  }
  // dHash collisions = visually identical images (very rare for genuinely
  // different photos — usually a real near-duplicate).
  const dhashIndex: Record<string, string[]> = {};
  for (const e of report.entries) {
    if (e.dhash) (dhashIndex[e.dhash] ??= []).push(e.file);
  }
  for (const [h, files] of Object.entries(dhashIndex)) {
    if (files.length > 1) {
      out.push({
        id: `signals.dhash_collision.${h}`,
        area: "consistency",
        severity: "warn",
        message: "Two or more files share the same dHash (visually identical)",
        actual: { dhash: h, files },
        hint: "Likely re-encoded duplicate — keep one or document why both are needed",
      });
    }
  }
  // Earlier we used dHash distance < 4 as a "near-duplicate" trigger and
  // raised it to danger. Visual verification proved this signal is too
  // coarse: at 8×8 grayscale the hash captures pose/framing more than
  // identity, so two genuinely different sessions of the same person in
  // the same profile pose can land at distance 2–3. We now only report
  // distance ≤ 2 as info ("similar composition") and rely on SHA-256
  // duplicates for actual byte-identical detection. A higher-resolution
  // pHash (or face-crop hash) is on the roadmap and will replace this.
  for (const p of report.closestDhashPairs ?? []) {
    if (p.distance <= 2) {
      out.push({
        id: `signals.similar_composition.${p.a}.${p.b}`,
        area: "consistency",
        severity: "info",
        message: "Pair of files has very similar composition (dHash distance ≤ 2)",
        actual: p,
        hint: "Compare visually: typically same pose/framing, not same content. Use SHA-256 duplicates for byte-identical detection.",
      });
    }
  }

  return out;
}

export async function loadSignalReportForUi(): Promise<SlimReport | null> {
  return loadReport();
}
